name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn eslint
      - run: yarn tsc
